version: '3'
services:
  backend:
    environment:
      - JAVA_MAXMEMORY=2048
      - JAVA_STARTMEMORY=2048
    build: ./backend
    ports:
      - "8080:8080"
    stdin_open: true
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
 